<template>
    <div id="wrapper">
        <main class="container">
            <h1 class="title is-1 has-text-centered">Steam Knight</h1>
            <hr>
            <h4 class="subtitle is-4 has-text-centered">
                Steam Knight is Steam client to help you manage multiple Steam accounts.
                <br>
                To keep your accounts secure you will need to enter a master password below.
            </h4>
            <hr>
            <div class="box">
                <div class="field">
                    <label class="label has-text-left">Master Password</label>
                    <p class="control has-icons-left">
                        <input v-model="masterPassword" class="input is-primary" type="text" placeholder="Master Password">
                        <span class="icon is-small is-left">
                          <i class="fa fa-lock"></i>
                        </span>
                    </p>
                </div>
                <div class="columns">
                    <div class="column has-text-left">
                        <a class="button is-primary" v-on:click="enter()">Enter</a>
                    </div>
                    <div class="column has-text-right">
                        <a class="button is-primary" v-on:click="$modal.show('info')">Click here for more information!</a>
                    </div>
                </div>
            </div>
        </main>
        <modal name="info" :adaptive="true" :width="1200" :height="650">
            <section class="section modal-box">
                <h1 class="title is-1 has-text-centered">Master Password</h1>
                <hr>
                <h1 class="subtitle is-3 has-text-centered">Why do I need a master password?</h1>
                <p class="subtitle is-5 has-text-centered">
                    This master password will encrypt your login credentials when they are saved.
                    <br>
                    When you start
                    Steam Knight back up again and enter your master password, it will begin logging your Steam accounts
                    back in.
                </p>
                <br>
                <h1 class="subtitle is-3 has-text-centered">What encryption methods are used?</h1>
                <p class="subtitle is-5 has-text-centered">
                    Steam Knight is an open-source client and encryption methods can be found on the Github repo.
                    <br>
                    The master password is hashed 10,000 times with sha512 and the resultant hash is used as the key
                    for the following encryption method.
                    <br>
                    The login details of the account are encrypted using the aes-256-cbc cipher algorithm with 16 randomly
                    generated bytes as the initialisation vector and the hashed master password as the key.
                    <br>
                    The username of the account is hashed with sha512 and is mapped to the encrypted data and saved
                    to a file.
                </p>
                <h1 class="subtitle is-3 has-text-centered">Does this completely secure my accounts?</h1>
                <p class="subtitle is-5 has-text-centered">
                    The only reason this client encrypts your login details is to make them harder to access
                    in the event the login details file is stolen. If attackers have stolen the file, chances
                    are your accounts and computer are compromised and the encryption of your login details is not
                    going to stop attackers gaining unauthorised access to your accounts.
                </p>
            </section>
        </modal>
    </div>
</template>

<script>
  import ScaleLoader from 'vue-spinner/src/ScaleLoader.vue';
  import SteamAccountManager from '../../components/SteamAccountManager';

  export default {
    name: 'account',
    components: { ScaleLoader },
    data() {
      return {
        masterPassword: '',
      };
    },
    methods: {
      enter() {
        SteamAccountManager.setKey(this.masterPassword);
        this.$router.push({ name: 'add-account' });
      },
    },
  };
</script>

<style src="font-awesome/css/font-awesome.min.css"></style>
<style scoped>
    @import url('https://fonts.googleapis.com/css?family=Source+Sans+Pro');

    #wrapper {
        padding: 20px 0px;
    }

    .modal-box {
        height: 100%;
        overflow-y: scroll;
    }

</style>
